# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the FaceKeep Windows tray app (ROADMAP 11.3).

Build via packaging/windows/build.ps1 (it prepares the venv, the icon, and
the optional staged tools, then runs PyInstaller on this spec and gates the
result on ``FaceKeep.exe --selftest``). The entry point is launcher.py ->
facekeep.app.main (the tray app); there is no console — stdio goes to
``~/.cache/facekeep/app.log`` (facekeep.app._redirect_stdio).
"""

from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, copy_metadata

HERE = Path(SPECPATH)  # noqa: F821 — SPECPATH is injected by PyInstaller

# --- Gradio under PyInstaller ------------------------------------------------
# gradio ships frontend/template assets as package data and inspects its own
# source at runtime, so it needs its data files collected AND collection as
# plain .py source (module_collection_mode below). gradio_client/safehttpx/
# groovy are its runtime companions; metadata rides along for the packages
# that resolve their own version via importlib.metadata.
datas = []
datas += collect_data_files("gradio")
datas += collect_data_files("gradio_client")
for pkg in ("safehttpx", "groovy"):
    try:
        datas += collect_data_files(pkg)
    except Exception:
        pass  # not present in this gradio generation
for pkg in ("gradio", "gradio_client", "safehttpx", "groovy"):
    try:
        datas += copy_metadata(pkg)
    except Exception:
        pass

# --- Bundled external tools (guardrail 4) -----------------------------------
# build.ps1 stages ffmpeg (and optionally libavif) under stage/tools/**; the
# app wires $FACEKEEP_FFMPEG / $FACEKEEP_AVIFENC to them at startup
# (facekeep.app.wire_bundled_tools — an env var the user set always wins).
# Nothing staged -> a smaller build whose video path degrades gracefully
# (videos are skipped with the install hint; photos unaffected).
stage = HERE / "stage"
if (stage / "tools").is_dir():
    for f in sorted((stage / "tools").rglob("*")):
        if f.is_file():
            datas.append((str(f), str(f.parent.relative_to(stage))))

# --- Never torch (guardrail 4) ----------------------------------------------
# The [ai] extra stays a pip-time opt-in; a packaged app must not carry it.
# build.ps1 additionally builds from a venv that never installs these AND
# fails the build if a torch artifact shows up in dist anyway — this exclude
# list is the belt, the venv is the suspenders.
excludes = [
    "torch", "torchvision", "torchaudio", "realesrgan", "basicsr", "gfpgan",
    "facexlib", "lpips", "codeformer", "mediapipe",
    "matplotlib", "IPython", "jupyter",
]

a = Analysis(
    [str(HERE / "launcher.py")],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=["pystray._win32"],  # pystray picks its backend dynamically
    hookspath=[],
    runtime_hooks=[],
    excludes=excludes,
    module_collection_mode={"gradio": "py"},
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="FaceKeep",
    icon=str(HERE / "FaceKeep.ico"),  # generated by make_icon.py (build.ps1)
    console=False,  # tray app; stdio -> ~/.cache/facekeep/app.log
    disable_windowed_traceback=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="FaceKeep",
)
